# Generated by Django 3.0.8 on 2020-07-11 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='interested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
