# Generated by Django 3.0.8 on 2020-07-12 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200710_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='interested',
        ),
        migrations.AddField(
            model_name='auction',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
