# Generated by Django 3.0.8 on 2020-07-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200712_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='auction', to='auctions.Category'),
        ),
    ]
